// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsMxDd5b3OSGTK1feEtq3s8Acw9GAccec',
    appId: '1:380695800660:web:7b9a11c03e79696ac3f6c1',
    messagingSenderId: '380695800660',
    projectId: 'raices-a8bcf',
    authDomain: 'raices-a8bcf.firebaseapp.com',
    storageBucket: 'raices-a8bcf.appspot.com',
    measurementId: 'G-44ZZFNKSNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdtMP6OyCtlCjnd42o0YPJxjPiRHHguA0',
    appId: '1:380695800660:android:fc6ce9e014edeec8c3f6c1',
    messagingSenderId: '380695800660',
    projectId: 'raices-a8bcf',
    storageBucket: 'raices-a8bcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCV8EbLgFRYThDQ5A5XB-UeTcPM6JAvc',
    appId: '1:380695800660:ios:1a46c3e261189424c3f6c1',
    messagingSenderId: '380695800660',
    projectId: 'raices-a8bcf',
    storageBucket: 'raices-a8bcf.appspot.com',
    iosBundleId: 'com.example.miPrimerProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCV8EbLgFRYThDQ5A5XB-UeTcPM6JAvc',
    appId: '1:380695800660:ios:1a46c3e261189424c3f6c1',
    messagingSenderId: '380695800660',
    projectId: 'raices-a8bcf',
    storageBucket: 'raices-a8bcf.appspot.com',
    iosBundleId: 'com.example.miPrimerProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsMxDd5b3OSGTK1feEtq3s8Acw9GAccec',
    appId: '1:380695800660:web:0c64ae82cae7b207c3f6c1',
    messagingSenderId: '380695800660',
    projectId: 'raices-a8bcf',
    authDomain: 'raices-a8bcf.firebaseapp.com',
    storageBucket: 'raices-a8bcf.appspot.com',
    measurementId: 'G-5ZXMDTNBJ7',
  );
}
